let resList = [
    {
      id: "1",
      name: "KFC",
      cloudinaryImageId: "qrqhfouxoeqt8aflj2yt",
      locality: "ITPL Main Road",
      areaName: "Whitefield",
      costForTwo: "₹300 for two",
      avgRating: 4.2,
      deliveryTime: 38,
      costForTwo: 400,
      cuisines: ["Chinese", "North Indian", "Punjabi"],
    },
    {
      id: "2",
      name: "Meghana",
      cloudinaryImageId: "u3w6zgapfaun4zyt5pxn",
      locality: "ITPL Main Road",
      areaName: "Whitefield",
      costForTwo: "₹300 for two",
      avgRating: 3.2,
      deliveryTime: 42,
      costForTwo: 250,
      cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
    },
    {
      id: "3",
      name: "Hyderbad house",
      cloudinaryImageId: "qrqhfouxoeqt8aflj2yt",
      locality: "ITPL Main Road",
      areaName: "Whitefield",
      costForTwo: "₹300 for two",
      avgRating: 4.62,
      deliveryTime: 25,
      costForTwo: 340,
      cuisines: ["Indian", "Chinese"],
    },
    {
      id: "4",
      name: "trinetra",
      cloudinaryImageId: "thzhbierhb2qxhqsl0bo",
      locality: "ITPL Main Road",
      areaName: "Whitefield",
      costForTwo: "₹300 for two",
      avgRating: 3.2,
      deliveryTime: 33,
      costForTwo: 400,
      cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
    },
    {
      id: "5",
      name: "KFC",
      cloudinaryImageId: "jwzxv4hmmnyuice4pe8x",
      locality: "ITPL Main Road",
      areaName: "Whitefield",
      costForTwo: "₹300 for two",
      avgRating: 4.2,
      deliveryTime: 38,
      costForTwo: 800,
      cuisines: ["Indian", "Chinese"],
    },
    {
      id: "6",
      name: "KFC",
      cloudinaryImageId: "qrqhfouxoeqt8aflj2yt",
      locality: "ITPL Main Road",
      areaName: "Whitefield",
      costForTwo: "₹300 for two",
      avgRating: 4.2,
      deliveryTime: 45,
      costForTwo: 600,
      cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
    },
  ];
  
export default resList;